<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageVersion Include="Moq" Version="4.16.1" />
    <PackageVersion Include="NUNit" Version="4.1.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.0.0" />
    <PackageVersion Include="CycloneDX" Version="4.2.0" />
  </ItemGroup>

</Project>